from enum import StrEnum


class UserRole(StrEnum):
    ADMIN_ELECTORAL = "ADMIN_ELECTORAL"
    CAPTURISTA = "CAPTURISTA"
    SUPERVISOR = "SUPERVISOR"
    AUDITOR = "AUDITOR"
    OBSERVADOR = "OBSERVADOR"
    CIUDADANO_PUBLICO = "CIUDADANO_PUBLICO"


class UserStatus(StrEnum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    SUSPENDED = "SUSPENDED"


class ActaStatus(StrEnum):
    DRAFT = "DRAFT"
    UPLOADED = "UPLOADED"
    HASHED = "HASHED"
    ANCHORED = "ANCHORED"
    UNDER_REVIEW = "UNDER_REVIEW"
    VERIFIED = "VERIFIED"
    REJECTED = "REJECTED"
    ARCHIVED = "ARCHIVED"


class DocumentIntegrityStatus(StrEnum):
    PENDING = "PENDING"
    VALID = "VALID"
    MISMATCH = "MISMATCH"
    CORRUPTED = "CORRUPTED"
    STORAGE_MISSING = "STORAGE_MISSING"
    ANCHORED = "ANCHORED"


class DocumentAccessStatus(StrEnum):
    PRIVATE = "PRIVATE"
    PUBLIC_VERIFIABLE = "PUBLIC_VERIFIABLE"
    RESTRICTED = "RESTRICTED"


class DocumentLifecycleStatus(StrEnum):
    UPLOADED = "UPLOADED"
    HASHED = "HASHED"
    STORED = "STORED"
    VERIFIED = "VERIFIED"
    ANCHORED = "ANCHORED"
    ARCHIVED = "ARCHIVED"


class CustodyEventType(StrEnum):
    CREATED = "CREATED"
    TRANSFERRED = "TRANSFERRED"
    RECEIVED = "RECEIVED"
    VALIDATED = "VALIDATED"
    REJECTED = "REJECTED"
    ESCALATED = "ESCALATED"
    CLOSED = "CLOSED"


class PREPValidationStatus(StrEnum):
    PENDING = "PENDING"
    MATCHED = "MATCHED"
    MISMATCHED = "MISMATCHED"
    REQUIRES_REVIEW = "REQUIRES_REVIEW"


class BlockchainVerificationStatus(StrEnum):
    PENDING = "PENDING"
    ANCHORED = "ANCHORED"
    VERIFIED = "VERIFIED"
    FAILED = "FAILED"


class BlockchainAnchorType(StrEnum):
    DOCUMENT_HASH = "DOCUMENT_HASH"
    CRITICAL_EVENT = "CRITICAL_EVENT"


class BlockchainProviderType(StrEnum):
    MOCK = "MOCK"
    HYPERLEDGER_FABRIC = "HYPERLEDGER_FABRIC"
    ETHEREUM = "ETHEREUM"
    POLYGON = "POLYGON"


class AuditEventCategory(StrEnum):
    AUTH = "AUTH"
    ACTA = "ACTA"
    DOCUMENT = "DOCUMENT"
    CUSTODY = "CUSTODY"
    PREP = "PREP"
    BLOCKCHAIN = "BLOCKCHAIN"
    SECURITY = "SECURITY"
    SYSTEM = "SYSTEM"
    VERIFICATION = "VERIFICATION"


class AuditEventSeverity(StrEnum):
    INFO = "INFO"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"


class AlertType(StrEnum):
    PREP_ACTA_MISMATCH = "PREP_ACTA_MISMATCH"
    DUPLICATE_ACTA = "DUPLICATE_ACTA"
    DUPLICATE_DOCUMENT_HASH = "DUPLICATE_DOCUMENT_HASH"
    DOCUMENT_HASH_MISMATCH = "DOCUMENT_HASH_MISMATCH"
    BLOCKCHAIN_HASH_MISMATCH = "BLOCKCHAIN_HASH_MISMATCH"
    CUSTODY_GAP = "CUSTODY_GAP"
    UNAUTHORIZED_STATE_TRANSITION = "UNAUTHORIZED_STATE_TRANSITION"
    STORAGE_OBJECT_MISSING = "STORAGE_OBJECT_MISSING"
    SUSPICIOUS_ACCESS = "SUSPICIOUS_ACCESS"
    MANUAL_REVIEW_REQUIRED = "MANUAL_REVIEW_REQUIRED"


class AlertStatus(StrEnum):
    OPEN = "OPEN"
    IN_REVIEW = "IN_REVIEW"
    RESOLVED = "RESOLVED"
    FALSE_POSITIVE = "FALSE_POSITIVE"
    ESCALATED = "ESCALATED"
