"""initial schema with blockchain anchors

Revision ID: 85f385df0ddb
Revises: 
Create Date: 2026-05-17 22:06:58.104594
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '85f385df0ddb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blockchain_anchors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('anchor_type', sa.Enum('DOCUMENT_HASH', 'CRITICAL_EVENT', name='blockchainanchortype', native_enum=False), nullable=False),
    sa.Column('hash_value', sa.String(length=64), nullable=False),
    sa.Column('blockchain_network', sa.String(length=120), nullable=False),
    sa.Column('provider', sa.Enum('MOCK', 'HYPERLEDGER_FABRIC', 'ETHEREUM', 'POLYGON', name='blockchainprovidertype', native_enum=False), nullable=False),
    sa.Column('transaction_hash', sa.String(length=200), nullable=True),
    sa.Column('block_number', sa.Integer(), nullable=True),
    sa.Column('channel_name', sa.String(length=120), nullable=True),
    sa.Column('chaincode_name', sa.String(length=120), nullable=True),
    sa.Column('anchored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_status', sa.Enum('PENDING', 'ANCHORED', 'VERIFIED', 'FAILED', name='blockchainverificationstatus', native_enum=False), nullable=False),
    sa.Column('request_payload', sa.JSON(), nullable=True),
    sa.Column('response_payload', sa.JSON(), nullable=True),
    sa.Column('anchored_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('length(hash_value) = 64', name='ck_anchor_hash_length'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blockchain_anchors_anchor_type'), 'blockchain_anchors', ['anchor_type'], unique=False)
    op.create_index(op.f('ix_blockchain_anchors_anchored_by'), 'blockchain_anchors', ['anchored_by'], unique=False)
    op.create_index(op.f('ix_blockchain_anchors_entity_id'), 'blockchain_anchors', ['entity_id'], unique=False)
    op.create_index(op.f('ix_blockchain_anchors_entity_type'), 'blockchain_anchors', ['entity_type'], unique=False)
    op.create_index(op.f('ix_blockchain_anchors_hash_value'), 'blockchain_anchors', ['hash_value'], unique=False)
    op.create_index(op.f('ix_blockchain_anchors_provider'), 'blockchain_anchors', ['provider'], unique=False)
    op.create_index(op.f('ix_blockchain_anchors_transaction_hash'), 'blockchain_anchors', ['transaction_hash'], unique=True)
    op.create_index(op.f('ix_blockchain_anchors_verification_status'), 'blockchain_anchors', ['verification_status'], unique=False)
    op.create_table('polling_stations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('polling_station_code', sa.String(length=80), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=False),
    sa.Column('municipality', sa.String(length=120), nullable=False),
    sa.Column('district', sa.String(length=40), nullable=False),
    sa.Column('section', sa.String(length=40), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('station_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('latitude IS NULL OR (latitude >= -90 AND latitude <= 90)', name='ck_polling_latitude'),
    sa.CheckConstraint('longitude IS NULL OR (longitude >= -180 AND longitude <= 180)', name='ck_polling_longitude'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_polling_stations_polling_station_code'), 'polling_stations', ['polling_station_code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN_ELECTORAL', 'CAPTURISTA', 'SUPERVISOR', 'AUDITOR', 'OBSERVADOR', 'CIUDADANO_PUBLICO', name='userrole', native_enum=False), nullable=False),
    sa.Column('organization', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='userstatus', native_enum=False), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('before_state', sa.JSON(), nullable=True),
    sa.Column('after_state', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=120), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('request_id', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('storage_provider', sa.String(length=80), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('uploaded_by', sa.String(length=36), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('integrity_status', sa.Enum('PENDING', 'VALID', 'MISMATCH', 'CORRUPTED', name='documentintegritystatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('file_size > 0', name='ck_documents_file_size_positive'),
    sa.CheckConstraint('length(sha256_hash) = 64', name='ck_documents_sha256_length'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_path')
    )
    op.create_index(op.f('ix_documents_sha256_hash'), 'documents', ['sha256_hash'], unique=True)
    op.create_table('actas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('acta_code', sa.String(length=120), nullable=False),
    sa.Column('polling_station_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'UPLOADED', 'HASHED', 'ANCHORED', 'UNDER_REVIEW', 'VERIFIED', 'REJECTED', 'ARCHIVED', name='actastatus', native_enum=False), nullable=False),
    sa.Column('election_type', sa.String(length=80), nullable=False),
    sa.Column('municipality', sa.String(length=120), nullable=False),
    sa.Column('district', sa.String(length=40), nullable=False),
    sa.Column('section', sa.String(length=40), nullable=False),
    sa.Column('expected_total_votes', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('blockchain_anchor_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['blockchain_anchor_id'], ['blockchain_anchors.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['polling_station_id'], ['polling_stations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blockchain_anchor_id'),
    sa.UniqueConstraint('document_id')
    )
    op.create_index(op.f('ix_actas_acta_code'), 'actas', ['acta_code'], unique=True)
    op.create_index(op.f('ix_actas_polling_station_id'), 'actas', ['polling_station_id'], unique=False)
    op.create_index(op.f('ix_actas_status'), 'actas', ['status'], unique=False)
    op.create_table('custody_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('acta_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.Enum('CREATED', 'TRANSFERRED', 'RECEIVED', 'VALIDATED', 'REJECTED', 'ESCALATED', 'CLOSED', name='custodyeventtype', native_enum=False), nullable=False),
    sa.Column('from_user_id', sa.String(length=36), nullable=True),
    sa.Column('to_user_id', sa.String(length=36), nullable=True),
    sa.Column('performed_by', sa.String(length=36), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('evidence_document_id', sa.String(length=36), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['acta_id'], ['actas.id'], ),
    sa.ForeignKeyConstraint(['evidence_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custody_events_acta_id'), 'custody_events', ['acta_id'], unique=False)
    op.create_index(op.f('ix_custody_events_created_at'), 'custody_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_custody_events_event_type'), 'custody_events', ['event_type'], unique=False)
    op.create_table('prep_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('acta_id', sa.String(length=36), nullable=False),
    sa.Column('polling_station_id', sa.String(length=36), nullable=False),
    sa.Column('captured_by', sa.String(length=36), nullable=False),
    sa.Column('candidate_results', sa.JSON(), nullable=False),
    sa.Column('total_votes', sa.Integer(), nullable=False),
    sa.Column('null_votes', sa.Integer(), nullable=False),
    sa.Column('valid_votes', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('validation_status', sa.Enum('PENDING', 'MATCHED', 'MISMATCHED', 'REQUIRES_REVIEW', name='prepvalidationstatus', native_enum=False), nullable=False),
    sa.Column('mismatch_reason', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['acta_id'], ['actas.id'], ),
    sa.ForeignKeyConstraint(['captured_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['polling_station_id'], ['polling_stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prep_results_acta_id'), 'prep_results', ['acta_id'], unique=False)
    op.create_index(op.f('ix_prep_results_polling_station_id'), 'prep_results', ['polling_station_id'], unique=False)
    op.create_index(op.f('ix_prep_results_validation_status'), 'prep_results', ['validation_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prep_results_validation_status'), table_name='prep_results')
    op.drop_index(op.f('ix_prep_results_polling_station_id'), table_name='prep_results')
    op.drop_index(op.f('ix_prep_results_acta_id'), table_name='prep_results')
    op.drop_table('prep_results')
    op.drop_index(op.f('ix_custody_events_event_type'), table_name='custody_events')
    op.drop_index(op.f('ix_custody_events_created_at'), table_name='custody_events')
    op.drop_index(op.f('ix_custody_events_acta_id'), table_name='custody_events')
    op.drop_table('custody_events')
    op.drop_index(op.f('ix_actas_status'), table_name='actas')
    op.drop_index(op.f('ix_actas_polling_station_id'), table_name='actas')
    op.drop_index(op.f('ix_actas_acta_code'), table_name='actas')
    op.drop_table('actas')
    op.drop_index(op.f('ix_documents_sha256_hash'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_polling_stations_polling_station_code'), table_name='polling_stations')
    op.drop_table('polling_stations')
    op.drop_index(op.f('ix_blockchain_anchors_verification_status'), table_name='blockchain_anchors')
    op.drop_index(op.f('ix_blockchain_anchors_transaction_hash'), table_name='blockchain_anchors')
    op.drop_index(op.f('ix_blockchain_anchors_provider'), table_name='blockchain_anchors')
    op.drop_index(op.f('ix_blockchain_anchors_hash_value'), table_name='blockchain_anchors')
    op.drop_index(op.f('ix_blockchain_anchors_entity_type'), table_name='blockchain_anchors')
    op.drop_index(op.f('ix_blockchain_anchors_entity_id'), table_name='blockchain_anchors')
    op.drop_index(op.f('ix_blockchain_anchors_anchored_by'), table_name='blockchain_anchors')
    op.drop_index(op.f('ix_blockchain_anchors_anchor_type'), table_name='blockchain_anchors')
    op.drop_table('blockchain_anchors')
    # ### end Alembic commands ###
