"""add audit traceability alerts

Revision ID: e2d84e333650
Revises: ec2c099d20d9
Create Date: 2026-05-17 22:33:06.660541
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e2d84e333650'
down_revision: Union[str, None] = 'ec2c099d20d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('alert_type', sa.Enum('PREP_ACTA_MISMATCH', 'DUPLICATE_ACTA', 'DUPLICATE_DOCUMENT_HASH', 'DOCUMENT_HASH_MISMATCH', 'BLOCKCHAIN_HASH_MISMATCH', 'CUSTODY_GAP', 'UNAUTHORIZED_STATE_TRANSITION', 'STORAGE_OBJECT_MISSING', 'SUSPICIOUS_ACCESS', 'MANUAL_REVIEW_REQUIRED', name='alerttype', native_enum=False), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='auditeventseverity', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_REVIEW', 'RESOLVED', 'FALSE_POSITIVE', 'ESCALATED', name='alertstatus', native_enum=False), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('acta_id', sa.String(length=36), nullable=True),
    sa.Column('polling_station_id', sa.String(length=36), nullable=True),
    sa.Column('detected_by', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('recommendation', sa.String(length=2000), nullable=True),
    sa.Column('assigned_to', sa.String(length=36), nullable=True),
    sa.Column('resolved_by', sa.String(length=36), nullable=True),
    sa.Column('resolution_notes', sa.String(length=2000), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['acta_id'], ['actas.id'], ),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['polling_station_id'], ['polling_stations.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_acta_id'), 'alerts', ['acta_id'], unique=False)
    op.create_index(op.f('ix_alerts_alert_type'), 'alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alerts_assigned_to'), 'alerts', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_alerts_entity_id'), 'alerts', ['entity_id'], unique=False)
    op.create_index(op.f('ix_alerts_entity_type'), 'alerts', ['entity_type'], unique=False)
    op.create_index(op.f('ix_alerts_polling_station_id'), 'alerts', ['polling_station_id'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.add_column('audit_logs', sa.Column('correlation_id', sa.String(length=120), nullable=True))
    op.add_column('audit_logs', sa.Column('actor_role', sa.String(length=80), nullable=True))
    op.add_column('audit_logs', sa.Column('actor_organization', sa.String(length=255), nullable=True))
    op.add_column('audit_logs', sa.Column('event_category', sa.Enum('AUTH', 'ACTA', 'DOCUMENT', 'CUSTODY', 'PREP', 'BLOCKCHAIN', 'SECURITY', 'SYSTEM', 'VERIFICATION', name='auditeventcategory', native_enum=False), server_default='SYSTEM', nullable=False))
    op.add_column('audit_logs', sa.Column('event_severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='auditeventseverity', native_enum=False), server_default='INFO', nullable=False))
    op.add_column('audit_logs', sa.Column('changed_fields', sa.JSON(), nullable=True))
    op.add_column('audit_logs', sa.Column('geo_location', sa.String(length=255), nullable=True))
    op.add_column('audit_logs', sa.Column('evidence_document_id', sa.String(length=36), nullable=True))
    op.add_column('audit_logs', sa.Column('related_acta_id', sa.String(length=36), nullable=True))
    op.add_column('audit_logs', sa.Column('related_polling_station_id', sa.String(length=36), nullable=True))
    op.add_column('audit_logs', sa.Column('blockchain_anchor_id', sa.String(length=36), nullable=True))
    op.add_column('audit_logs', sa.Column('hash_value', sa.String(length=64), nullable=True))
    op.add_column('audit_logs', sa.Column('metadata_json', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_audit_logs_actor_role'), 'audit_logs', ['actor_role'], unique=False)
    op.create_index(op.f('ix_audit_logs_blockchain_anchor_id'), 'audit_logs', ['blockchain_anchor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_correlation_id'), 'audit_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_category'), 'audit_logs', ['event_category'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_severity'), 'audit_logs', ['event_severity'], unique=False)
    op.create_index(op.f('ix_audit_logs_evidence_document_id'), 'audit_logs', ['evidence_document_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_hash_value'), 'audit_logs', ['hash_value'], unique=False)
    op.create_index(op.f('ix_audit_logs_related_acta_id'), 'audit_logs', ['related_acta_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_related_polling_station_id'), 'audit_logs', ['related_polling_station_id'], unique=False)
    op.create_foreign_key('fk_audit_logs_blockchain_anchor_id', 'audit_logs', 'blockchain_anchors', ['blockchain_anchor_id'], ['id'])
    op.create_foreign_key('fk_audit_logs_evidence_document_id', 'audit_logs', 'documents', ['evidence_document_id'], ['id'])
    op.create_foreign_key('fk_audit_logs_related_acta_id', 'audit_logs', 'actas', ['related_acta_id'], ['id'])
    op.create_foreign_key('fk_audit_logs_related_polling_station_id', 'audit_logs', 'polling_stations', ['related_polling_station_id'], ['id'])
    op.alter_column('audit_logs', 'event_category', server_default=None)
    op.alter_column('audit_logs', 'event_severity', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_audit_logs_related_polling_station_id', 'audit_logs', type_='foreignkey')
    op.drop_constraint('fk_audit_logs_related_acta_id', 'audit_logs', type_='foreignkey')
    op.drop_constraint('fk_audit_logs_evidence_document_id', 'audit_logs', type_='foreignkey')
    op.drop_constraint('fk_audit_logs_blockchain_anchor_id', 'audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_audit_logs_related_polling_station_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_related_acta_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_hash_value'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_evidence_document_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_severity'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_category'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_correlation_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_blockchain_anchor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_role'), table_name='audit_logs')
    op.drop_column('audit_logs', 'metadata_json')
    op.drop_column('audit_logs', 'hash_value')
    op.drop_column('audit_logs', 'blockchain_anchor_id')
    op.drop_column('audit_logs', 'related_polling_station_id')
    op.drop_column('audit_logs', 'related_acta_id')
    op.drop_column('audit_logs', 'evidence_document_id')
    op.drop_column('audit_logs', 'geo_location')
    op.drop_column('audit_logs', 'changed_fields')
    op.drop_column('audit_logs', 'event_severity')
    op.drop_column('audit_logs', 'event_category')
    op.drop_column('audit_logs', 'actor_organization')
    op.drop_column('audit_logs', 'actor_role')
    op.drop_column('audit_logs', 'correlation_id')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_polling_station_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_entity_type'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_entity_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_assigned_to'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_type'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_acta_id'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
