"""add document storage pipeline fields

Revision ID: ec2c099d20d9
Revises: 85f385df0ddb
Create Date: 2026-05-17 22:17:04.169081
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ec2c099d20d9'
down_revision: Union[str, None] = '85f385df0ddb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('original_file_name', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('mime_type', sa.String(length=100), nullable=True))
    op.add_column('documents', sa.Column('storage_bucket', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('storage_key', sa.String(length=1000), nullable=True))
    op.add_column('documents', sa.Column('storage_url', sa.String(length=2000), nullable=True))
    op.add_column('documents', sa.Column('access_status', sa.Enum('PRIVATE', 'PUBLIC_VERIFIABLE', 'RESTRICTED', name='documentaccessstatus', native_enum=False), nullable=False, server_default='PRIVATE'))
    op.add_column('documents', sa.Column('lifecycle_status', sa.Enum('UPLOADED', 'HASHED', 'STORED', 'VERIFIED', 'ANCHORED', 'ARCHIVED', name='documentlifecyclestatus', native_enum=False), nullable=False, server_default='UPLOADED'))
    op.add_column('documents', sa.Column('metadata_json', sa.JSON(), nullable=True))
    op.add_column('documents', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('documents', sa.Column('last_integrity_check_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('documents', 'integrity_status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('PENDING', 'VALID', 'MISMATCH', 'CORRUPTED', 'STORAGE_MISSING', 'ANCHORED', name='documentintegritystatus', native_enum=False),
               existing_nullable=False)
    op.create_index(op.f('ix_documents_access_status'), 'documents', ['access_status'], unique=False)
    op.create_index(op.f('ix_documents_lifecycle_status'), 'documents', ['lifecycle_status'], unique=False)
    op.create_index(op.f('ix_documents_mime_type'), 'documents', ['mime_type'], unique=False)
    op.create_index(op.f('ix_documents_storage_key'), 'documents', ['storage_key'], unique=True)
    op.create_index(op.f('ix_documents_storage_provider'), 'documents', ['storage_provider'], unique=False)
    op.alter_column('documents', 'access_status', server_default=None)
    op.alter_column('documents', 'lifecycle_status', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_storage_provider'), table_name='documents')
    op.drop_index(op.f('ix_documents_storage_key'), table_name='documents')
    op.drop_index(op.f('ix_documents_mime_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_lifecycle_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_access_status'), table_name='documents')
    op.alter_column('documents', 'integrity_status',
               existing_type=sa.Enum('PENDING', 'VALID', 'MISMATCH', 'CORRUPTED', 'STORAGE_MISSING', 'ANCHORED', name='documentintegritystatus', native_enum=False),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
    op.drop_column('documents', 'last_integrity_check_at')
    op.drop_column('documents', 'verified_at')
    op.drop_column('documents', 'metadata_json')
    op.drop_column('documents', 'lifecycle_status')
    op.drop_column('documents', 'access_status')
    op.drop_column('documents', 'storage_url')
    op.drop_column('documents', 'storage_key')
    op.drop_column('documents', 'storage_bucket')
    op.drop_column('documents', 'mime_type')
    op.drop_column('documents', 'original_file_name')
    # ### end Alembic commands ###
